config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  get '/export', to: 'export#prepare'
  post '/export', to: 'export#export'
  get '/import', to: 'import#prepare'
  post '/import', to: 'import#import'
  get '/import_banking_statement', to: 'banking_statement_import#prepare'
  post '/import_banking_statement', to: 'banking_statement_import#import'
  get '/sepa_export', to: 'sepa_export#verify'
  post '/sepa_export', to: 'sepa_export#export'

  post '/admin/privileged_mode', to: 'admin#enable_privileged_mode'
  post '/admin/standard_mode', to: 'admin#disable_privileged_mode'

  get '/outstanding_payments', action: :show, controller: 'outstanding_payments'
  get '/finance_review', action: :show, controller: 'finance_review'

  resources :versions, only: %i[index show] do
    patch 'revert', to: 'versions#revert', on: :member
  end

  concern :versionable do
    resources :versions, only: %i[index show] do
      get 'diff', to: 'versions#diff'
      get 'diff/:after_id', to: 'versions#diff'
      patch 'revert', to: 'versions#revert'
    end
  end

  resources :password_resets # TODO: only

  get '/people_as_table', to: 'people#index_as_table'
  get '/events_as_table', to: 'events#index_as_table'

  root 'static#index'

  resources :people, concerns: :versionable do
    member do
      get 'addresses'
      get 'registrations'
      get 'privacy'
      get 'payments'
      get 'sepa_mandate'
      get 'groups'

      get 'edit_addresses'
      get 'edit_privacy'
      get 'edit_payments'
      get 'edit_sepa_mandate'
      delete 'delete_sepa_mandate', to: 'people#destroy_sepa_mandate'
      get 'edit_groups'

      get 'activate'
      post 'archive', to: 'people#archive'
    end
  end

  resources :registrations, concerns: :versionable do
    member do
      post 'self', to: 'registrations#create_self'
      get 'self', to: 'registrations#edit_self'
      put 'self', to: 'registrations#update_self'
      patch 'self', to: 'registrations#update_self'
      post 'pay_rest', to: 'registrations#pay_rest'
      get 'invitation', to: 'registrations#view_invitation', as: 'view_invitation'
    end
  end

  resources :events, concerns: :versionable do
    member do
      get 'registrations_as_table'
      get 'edit_own_registration'
      get 'edit_payments'
      get 'finances'
    end

    get 'register_other', to: 'registrations#select_person', as: 'select_person'
    post 'register_other', to: 'registrations#with_selected_person'
    get 'register_other/:person_id', to: 'registrations#new', as: 'register_person'
    post 'register_other/:person_id', to: 'registrations#create'
    get 'register_self', to: 'registrations#new_self'
    post 'register_self', to: 'registrations#create_self'
  end

  resources :generic_payments, concerns: :versionable
  resources :hostels, concerns: :versionable
  resources :groups, concerns: :versionable
  resources :mailinglists, concerns: :versionable

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  include PeopleHelper

  breadcrumb Person.model_name.human(count: :other), :people_path

  before_action :set_all_people, only: %i[index index_as_table]
  before_action :set_person, only: %i[
    show addresses registrations privacy payments sepa_mandate groups
    edit edit_addresses edit_privacy edit_payments edit_sepa_mandate edit_groups update
    archive destroy destroy_sepa_mandate
  ]
  before_action :basic_authorization

  def index; end

  def index_as_table
    render 'as_table'
  end

  # TODO: Optimierung mit "include"
  def show; end

  def new
    @person = Person.new
    @person_policy = policy(@person)
  end

  def edit; end

  def edit_addresses; end

  def edit_privacy; end

  def edit_payments; end

  def edit_groups; end

  def edit_sepa_mandate; end

  def create
    @person = Person.new(permitted_attributes(Person))
    @person_policy = policy(@person)
    if @person.save
      Rails.configuration.qeddb_hooks[:person_created].call(@person)
      if @person.active
        @person.generate_reset_password_token!
        mailer = AccountMailer.with(person: @person)
        mailer.account_created_email.deliver_now
      end
      redirect_to @person, notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @person.update(permitted_attributes(@person))
      redirect_to @person, notice: t('.success')
    else
      pages = %w[edit edit_addresses edit_payments edit_privacy edit_sepa_mandate]
      action = pages.include?(params[:formular]) ? params[:formular] : 'edit'
      render action
    end
  end

  # Nutzer datenschutzkonform löschen
  def archive
    authorize @person, :archive_person?
    @person.update(
      archived: true,
      active: false,
      email_address: nil,
      newsletter: false,
      photos_allowed: false,
      publish_birthday: false,
      publish_email: false,
      publish_address: false,
      publish: false,
      railway_station: nil,
      railway_discount: nil,
      meal_preference: nil,
      comment: nil,
      addresses: [],
      contacts: [],
      sepa_mandate: nil,
    )
    @person.registrations.update_all(
      arrival: nil,
      departure: nil,
      station_arrival: nil,
      station_departure: nil,
      railway_discount: nil,
      meal_preference: nil,
      comment: nil,
    )
    redirect_to @person, notice: t('.success')
  end

  def destroy
    authorize @person, :delete_person?
    @person.destroy
    Rails.configuration.qeddb_hooks[:person_deleted].call(@person)
    redirect_to people_url, notice: t('.success')
  end

  def destroy_sepa_mandate
    authorize @person, :edit_payments?
    @person.sepa_mandate = nil
    redirect_to @person, notice: t('.success')
  end

  private

  def set_person
    @person = policy_scope(Person).find(params[:id])
    @person_policy = policy(@person)
    breadcrumb @person.full_name, @person
    unless action_name == 'show'
      breadcrumb t("actions.person.#{action_name}"), { action: action_name }
    end
  end

  def set_all_people
    sort_field = ["first_name", "last_name"].include?(params[:sort]) ? params[:sort] : 'last_name'
    @people = policy_scope(Person).includes(:addresses, :contacts).reorder(sort_field)
    @person_policy = policy(Person)
    @current_sort = sort_field.to_s
  end

  def basic_authorization
    case action_name.to_sym
    when :show, :registrations
      authorize @person, :view_public?
    when :privacy, :groups
      authorize @person, :view_settings?
    when :payments, :sepa_mandate
      authorize @person, :view_payments?
    when :addresses
      authorize @person, :view_additional?
    when :edit, :update
      authorize @person, :edit_basic?
    when :edit_privacy
      authorize @person, :edit_settings?
    when :edit_payments, :edit_sepa_mandate
      authorize @person, :edit_payments?
    when :destroy_sepa_mandate
      Rails.logger.debug @person.inspect
      Rails.logger.debug action_name
      authorize @person, :edit_payments?
    when :edit_addresses
      authorize @person, :edit_additional?
    when :new, :create
      authorize Person, :edit_other?
    when :index, :index_as_table
      authorize Person, :list_members?
    when :destroy
      authorize @person, :delete_person?
    when :archive
      authorize @person, :archive_person?
    else
      raise Pundit::NotAuthorizedError({ query: action_name, record: @person })
    end
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def person_link(person)
    if policy(person).view_public?
      link_to person.full_name, person_path(person)
    else
      person.full_name
    end
  end

  # Effizientere Version ohne Rechteprüfung (wird für /people/ gebraucht)
  def person_link_unchecked(person)
    link_to person.full_name, person_path(person)
  end

  def new_person_link
    return nil unless policy(Person).edit_other?

    icon_button 'Neue Person eintragen', :person_add, new_person_path
  end

  def people_link
    return nil unless policy(Person).list_members?

    link_to Person.model_name.human(count: :other), people_path
  end

  def edit_general_person_link(person)
    return nil unless policy(person).edit_basic?

    icon_button t('actions.person.edit_general'), :edit, edit_person_path(person)
  end

  def edit_addresses_person_link(person)
    return nil unless policy(person).edit_additional?

    icon_button t('actions.person.edit_addresses'), :mail, edit_addresses_person_path(person)
  end

  def edit_privacy_person_link(person)
    return nil unless policy(person).edit_settings?

    icon_button t('actions.person.edit_privacy'), :security, edit_privacy_person_path(person)
  end

  def edit_payments_person_link(person)
    return nil unless policy(person).edit_payments?

    icon_button t('actions.person.edit_payments'), :euro, edit_payments_person_path(person)
  end

  def edit_sepa_mandate_person_link(person)
    return nil unless policy(person).edit_payments?

    icon_button t('actions.person.edit_sepa_mandate'), :euro, edit_sepa_mandate_person_path(person)
  end

  def delete_sepa_mandate_link(person)
    return nil unless policy(person).edit_payments?

    link_to delete_sepa_mandate_person_path(person),
            method: :delete,
            class: 'button',
            data: { confirm: "SEPA-Mandat von „#{person.full_name}“ löschen?" } do
      concat mi.shape(:delete).md_24
      concat t('actions.person.delete_sepa_mandate')
    end
  end

  def delete_person_link(person)
    return nil unless policy(person).delete_person?

    link_to person, method: :delete, class: 'button',
                    data: { confirm: format('Person „%s“ löschen?', person.full_name) } do
      concat mi.shape(:delete).md_24
      concat t('actions.person.delete')
    end
  end

  def archive_person_link(person)
    return nil unless policy(person).archive_person?

    form_with url: send('archive_person_path', person),
                    data: { confirm: format('Person „%s“ löschen?', person.full_name) } do
      button_tag class: 'button' do
        concat tag.i(class: 'material-icons md-24') { 'delete' }
        concat t('actions.person.archive')
      end
    end
  end
end

app/views/people/_additional_information_fieldset.erb
<fieldset id="person_additional_information_fieldset">
	<legend><%= t 'sections.person.additional_information' %></legend>

	<label>
		<%= Person.human_attribute_name(:railway_station) %>
		<i>Voreinstellung für den  Anreisebahnhof</i>
		<%= form.text_field :railway_station, id: :person_railway_station %>
	</label>

	<label>
		<%= Person.human_attribute_name(:railway_discount) %>
		<i>Für Ermäßigungen wie BahnCard oder Semesterticket</i>
		<%= form.text_field :railway_discount, id: :person_railway_discount %>
	</label>

	<label>
		<%= Person.human_attribute_name(:meal_preference) %>
		<i>Für besondere Essenwünsche wie Vegetarier oder Allergien</i>
		<%= form.text_area :meal_preference, id: :person_meal_preference, rows: 3, cols: 50 %>
	</label>

	<label>
		<%= Person.human_attribute_name(:comment) %>
		<i>Freifeld für beliebige weitere Informationen</i>
		<%= form.text_area :comment, id: :person_comment, rows: 3, cols: 50 %>
	</label>
</fieldset>

app/views/people/_addresses_fieldset.erb
<fieldset id="person_addresses_fieldset">
	<legend><%= Address.model_name.human(count: :other) =%></legend>
	<%= form.fields_for :addresses do |af| %>
		<%= af.options[:child_index] == 0 ?
			"Hier kann man den Hauptwohnsitz angeben:" :
			"Hier kann man eine weitere Adresse angeben:" %>
		<%= render partial: 'addresses/address_fields', locals: {form: af} %>
	<% end %>
</fieldset>

app/views/people/_contacts_fieldset.erb
<fieldset id="person_contacts_fieldset">
	<legend><%= Contact.model_name.human(count: :other) %></legend>

	<p>Für weitere Kontaktmöglichkeiten wie Telefonnummern, Email und Instant Messenger:</p>

	<%= form.fields_for :contacts do |cf| %>
		<%= render partial: 'contacts/contact_fields', locals: {form: cf} %>
	<% end %>

	<p><i>Einträge mit Typ "Mobil" werden auch in Teilnehmerlisten von Veranstaltungen angezeigt.</i></p>

	<datalist id="protocol_list">
		<%= im_protocol_list.map{|protocol| tag.option value: protocol}.join.html_safe %>
	</datalist>
</fieldset>

app/views/people/_general_fieldset.erb
<% ro_personal = !@person_policy.edit_personal? %>
<% ro_settings = !@person_policy.edit_settings? %>

<fieldset id="person_general_information_fieldset">
	<legend><%= t 'sections.person.generalinfo' %></legend>
	<div class="aligned">
	<%= form.label :account_name %>
	<!-- Hier muss der Accountname stehen, welcher zum Login benutzt wird. -->
	<%= form.text_field :account_name, id: :person_account_name, disabled: ro_personal %>

	<% if @person_policy.view_private? || @person.publish_email %>
		<%= form.label :email_address %>
		<%= form.email_field :email_address, id: :person_email_address, disabled: ro_settings %>
	<% end %>

	<% if @person_policy.edit_password? && mode == :edit %>
		<%= form.label :password %>
		<%= form.password_field :password, id: :person_password %>

		<%= form.label :password_confirmation %>
		<%= form.password_field :password_confirmation, id: :person_password_confirmation %>
	<% end %>

	<%= form.label :first_name %>
	<%= form.text_field :first_name, id: :person_first_name, disabled: ro_personal %>

	<%= form.label :last_name %>
	<%= form.text_field :last_name, id: :person_last_name, disabled: ro_personal %>

	<% if @person_policy.view_private? || @person.publish_birthday %>
		<%= form.label :birthday %>
		<%= form.date_field :birthday, id: :person_birthday, disabled: ro_personal %>
	<% end %>

	<%= form.label :gender %>
	<%= form.select :gender, Person.human_enum_options(:genders),
		{}, id: :person_gender, disabled: ro_personal %>


	<%= form.label :joined %>
	<%= form.date_field :joined, id: :person_joined, disabled: ro_personal %>

	<%= form.label :quitted %>
	<%= form.date_field :quitted, id: :person_quitted, disabled: ro_personal %>
	</div>
	<hr>
	<label>
		<%= form.check_box :active, id: :person_active, disabled: ro_personal %>
		<%= Person.human_attribute_name :active %>
		<i>Aktivierte Benutzer können sich selbständig in die Datenbank einloggen.</i>
	</label>
	<label>
		<%= form.check_box :archived, id: :person_archived, disabled: ro_personal %>
		<%= Person.human_attribute_name :archived %>
		<i>Archivierte Benutzer sind nicht mehr in der Datenbank zu finden.</i>
	</label>
</fieldset>

app/views/people/_payments_fieldset.erb
<fieldset id="person_payments_fieldset">
	<legend><%= Payment.model_name.human(count: :other) =%></legend>
	<div class="actions">
		<%= form.submit t('people.edit_payments.submit') %>
	</div>
	Hier kann man gezahlte Mitgliedsbeiträge eintragen:
	<%= form.fields_for :payments, @person.payments.reverse do |payment| %>
		<%= render partial: 'payments/payment_fields', locals: {form: payment} %>
	<% end %>
</fieldset>

app/views/people/_privacy_fieldset.erb
<fieldset id="person_privacy_fieldset">
    An dieser Stelle könnt ihr einstellen, welche Informationen von euch in der Mitgliederliste veröffentlicht werden.<br/>
    Für die vereinsinterne Vernetzung ist es hilfreich, wenn zumindest einige euer Kontaktdaten einsehbar sind.

	<label>
		<%= form.check_box :newsletter, id: :person_newsletter %>
		<%= Person.human_attribute_name :newsletter %>
		<i>Verschicke regelmäßige Newsletter meine Emailadresse.</i>
	</label>

	<label>
		<%= form.check_box :publish, id: :person_publish %>
		<%= Person.human_attribute_name :publish %>
		<i>Mache mein Profil in der Mitgliederliste öffentlich.</i>
	</label>

	<label>
		<%= form.check_box :publish_birthday, id: :person_publish_birthday %>
		<%= Person.human_attribute_name :publish_birthday %>
		<i>Zeige Geburtstag anderen Mitgliedern an.</i>
	</label>

	<label>
		<%= form.check_box :publish_email, id: :person_publish_email %>
		<%= Person.human_attribute_name :publish_email %>
		<i>Zeige Emailadresse anderen Mitgliedern an.</i>
	</label>

	<label>
		<%= form.check_box :publish_address, id: :person_publish_address %>
		<%= Person.human_attribute_name :publish_address %>
		<i>Zeige Adress- und Kontaktdaten anderen Mitgliedern an.</i>
	</label>
</fieldset>

app/views/people/as_table.html.erb
<% provide :title, Person.model_name.human(count: :other) %>
<h1><%= Person.model_name.human(count: :other) =%></h1>

<% if @person_policy.list_members? %>

<section id="people_data">

<div class="flexlayout">
<fieldset>
	<legend>Ansicht konfigurieren</legend>
	<div class="flexlayout">
	<fieldset>
		<label>Personen auswählen</label>
		<%= checkbox("show_member_row", "Mitglieder anzeigen", true) %>
		<%= checkbox("show_non_member_row", "Nichtmitglieder anzeigen", true) %>
	</fieldset>
	<fieldset>
		<label>Informationen auswählen</label>
		<%= checkbox("show_person_field", "Geschlecht und Geburtstag", true) %>
		<%= checkbox("show_phone_field", "Handynummer", true) %>
		<%= checkbox("show_email_field", "Emailadresse", true) %>
		<%= checkbox("show_address_field", "Addressdaten", true) %>
		<%= checkbox("show_account_field", "Benutzerkonto", false) %>
		<%= checkbox("show_status_field", "Mitgliedsstatus", false) %>
		<% if @person_policy.view_payments? %>
		  <%= checkbox("show_payment_field", "Zahlungsstatus", false) %>
		<% end %>
	</fieldset>
	</div>
	<div class="actions">
		<%= download_table_button('#people_table') %>
	</div>
</fieldset>
</div>

<table class="indexed_table" id="people_table">
	<thead>
		<tr>
			<th>#</th>
			<th data-sort="string"><%= Person.human_attribute_name :first_name %></th>
			<th data-sort="string"><%= Person.human_attribute_name :last_name %></th>
			<th data-sort="string" class="person_field"><%= Person.human_attribute_name :gender %></th>
			<th data-sort="string" class="person_field"><%= Person.human_attribute_name :birthday %></th>
			<th data-sort="string" class="email_field"><%= Person.human_attribute_name :email_address %></th>
			<th data-sort="string" class="address_field"><%= Person.human_attribute_name :main_address %></th>
			<th data-sort="string" class="phone_field"><%= Person.human_attribute_name :mobile_phone %></th>
			<th data-sort="int"    class="account_field"><%= Person.human_attribute_name :id %></th>
			<th data-sort="string" class="account_field"><%= Person.human_attribute_name :account_name %></th>
			<th data-sort="string" class="account_field"><%= Person.human_attribute_name :active %></th>
			<th data-sort="string" class="status_field"><%= Person.human_attribute_name :member %></th>
			<th data-sort="string" class="status_field"><%= Person.human_attribute_name :joined %></th>
			<th data-sort="string" class="status_field"><%= Person.human_attribute_name :quitted %></th>
			<% if @person_policy.view_payments? %>
			<th data-sort="string" class="payment_field"><%= Person.human_attribute_name :paid_until %></th>
			<% end %>
		</tr>
	</thead>

	<tbody>
		<% @people.each do |person| %>
			<tr class="<%= person.member? ? 'member_row' : 'non_member_row' %>">
				<td></td>
				<% if @person_policy.view_private? || person.publish %>
				<td><%= link_to person.first_name, person %></td>
				<td><%= link_to person.last_name, person %></td>
				<% else %>
				<td><%= person.first_name %></td>
				<td><%= person.last_name %></td>
				<% end %>

				<td class="person_field"><%= Person.human_enum_value(:gender, person.gender) %></td>

				<% if @person_policy.view_private? || (person.publish && person.publish_birthday) %>
					<td class="person_field" data-sort-value="<%= person.birthday %>">
						<%= render_date person.birthday %>
					</td>
				<% else %>
					<td class="person_field"><%= tag.i "privat" %></td>
				<% end %>


				<td class="email_field">
					<% if @person_policy.view_private? || (person.publish && person.publish_email) %>
						<%= mail_to person.email_address %>
					<% else %>
						<%= tag.i "privat" %>
					<% end %>
				</td>

				<td class="address_field">
					<% if @person_policy.view_private? || (person.publish && person.publish_address) %>
						<%= check_unknown(person.main_address) {|a| render_inline_address(a)}	%>
					<% else %>
						<%= tag.i "privat" %>
					<% end %>
				</td>

				<td class="phone_field">
					<% if @person_policy.view_private? || (person.publish && person.publish_address) %>
						<%= check_unknown(person.mobile_number) {|n| mobile_phone_html(n)}	%>
					<% else %>
						<%= tag.i "privat" %>
					<% end %>
				</td>

				<td class="account_field">
					<%= person.id %>
				</td>

				<td class="account_field">
					<%= person.account_name %>
				</td>

				<td class="account_field">
					<%= render_yes_no(person.active) %>
				</td>

				<td class="status_field">
					<%= render_yes_no(person.member?) %>
				</td>

				<td class="status_field" data-sort-value="<%= person.joined %>">
					<%= render_date person.joined %>
				</td>

				<td class="status_field" data-sort-value="<%= person.quitted %>">
					<%= render_date person.quitted %>
				</td>

				<% if @person_policy.view_payments? %>
					<td class="payment_field" data-sort-value="<%= person.paid_until %>"><%= render_date(person.paid_until) %></td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>
</section>

<script>
$(function(){
	$("#people_table").stupidtable();
	$('#people_data input[type=checkbox]').each(function(index, item) {updateVisibility(item)})})
$('#people_data input[type=checkbox]').click(function() {updateVisibility(this)});
</script>

<% end %>

app/views/people/edit.html.erb
<div class="flexlayout">
<%= form_with(model: @person, local: true) do |form| %>
	<%= hidden_field_tag 'formular', 'edit' %>
	<%= render partial: "shared/errors", locals: {object: @person} %>
	<fieldset>
	<div class="flexlayout">
		<%= render partial: 'general_fieldset', locals: {form: form, mode: :edit} %>
		<% if @person_policy.edit_additional? %>
			<%= render partial: 'additional_information_fieldset', locals: {form: form} %>
		<% end %>
	</div>
	<div class="actions">
		<%= form.submit %>
	</div>
	</fieldset>
<% end %>
</div>

app/views/people/edit_addresses.erb
<% 	@person.addresses.build; 3.times {@person.contacts.build} %>

<% if @person_policy.edit_additional? %>
<div class="flexlayout">
<%= form_with(model: @person, local: true) do |form| %>
	<%= hidden_field_tag 'formular', 'edit_addresses' %>
	<%= render partial: "shared/errors", locals: {object: @person} %>
	<fieldset>
	<div class="flexlayout">
		<%= render partial: 'addresses_fieldset', locals: {form: form} %>
		<%= render partial: 'contacts_fieldset', locals: {form: form} %>
	</div>
	<div class="actions">
		<%= form.submit t('.submit') %>
	</div>
	</fieldset>
<% end %>
</div>
<% end %>

app/views/people/edit_payments.erb
<% 1.times {@person.payments.build} %>

<% if @person_policy.edit_payments? %>
<div class="flexlayout">
<%= form_with(model: @person, local: true) do |form| %>
	<%= hidden_field_tag 'formular', 'edit_payments' %>
	<fieldset>
	<%= render partial: "shared/errors", locals: {object: @person} %>
	<%= render partial: 'payments_fieldset', locals: {form: form} %>
	</fieldset>
<% end %>
</div>

<script>
	const membership_fee = <%= Rails.configuration.membership_fee %>;

	function setDate(elem) {
		if(elem.id.endsWith("end")) {
			const start_year = ($("#" + elem.id.replace("end", "start"))[0]?.valueAsDate ?? new Date()).getFullYear();
			const amount = $("#" + elem.id.replace("end", "amount"))[0]?.valueAsNumber;
			const years = Number.isNaN(amount) ? 1 : amount / membership_fee;

			elem.value = `${start_year + years - 1}-12-31`;
		} else if(elem.id.endsWith("start")) {
			// Using valueAsDate here is horribly annoying with respect to time zones (just assigning new Date(year, 0, 1) will produce spam)
			elem.value = `${(new Date()).getFullYear()}-01-01`;
		} else {
			setToToday(elem);
		}
	}
	enableDateSetting({setter: setDate});
</script>
<% end %>

app/views/people/edit_privacy.erb
<% if @person_policy.edit_settings? %>
<div class="flexlayout">
<%= form_with(model: @person, local: true) do |form| %>
	<fieldset>
	<legend><%= t 'sections.person.settings' %></legend>
	<%= hidden_field_tag 'formular', 'edit_privacy' %>
	<%= render partial: "shared/errors", locals: {object: @person} %>
	<%= render partial: 'privacy_fieldset', locals: {form: form} %>
	<div class="actions">
		<%= form.submit t('.submit') %>
	</div>
	</fieldset>
<% end %>
</div>
<% end %>

app/views/people/edit_sepa_mandate.erb
<% if @person_policy.edit_payments? %>
  <div class="flexlayout">
    <%= form_with(model: @person, local: true) do |form| %>
      <%= hidden_field_tag "formular", "edit_sepa_mandate" %>
      <fieldset>
        <%= render partial: "shared/errors", locals: { object: @person } %>
        <%= render partial: "sepa_mandate_fieldset", locals: { form: form } %>
        <div class="actions">
          <%= form.submit t(".submit") %>
          <%= delete_sepa_mandate_link(@person) %>
        </div>
      </fieldset>
    <% end %>
  </div>
<% end %>

app/views/people/index.html.erb
<% provide :title, Person.model_name.human(count: :other) %>

<%
sort_field = @current_sort
categories = {}
@people.each {|person|
    category_value = person.send(sort_field)
	letter = category_value[0] || " "
	letter.upcase!
	categories[letter] = [] if categories[letter].nil?
	categories[letter].push person
}
show_unpublished_people = policy(Person).view_unpublished?
%>

<article id="people">
	<h1><%= Person.model_name.human(count: :other) %></h1>

	<div class="sort-controls">
		<span class="sort-label">Sortieren nach:</span>
		<div class="sort-buttons">
			<%= link_to 'Vorname', people_path(sort: 'first_name'),
			    class: ['sort-option', (@current_sort == 'first_name' ? 'active' : nil)] %>
			<%= link_to 'Nachname', people_path(sort: 'last_name'),
			    class: ['sort-option', (@current_sort == 'last_name' ? 'active' : nil)] %>
		</div>
	</div>

	<div class="overview">
		<dl>
			<% categories.keys.sort.each do |key| %>
				<div>
					<dt><%= key %></dt>
					<% categories[key].each do |person| %>
						<% if person.publish || show_unpublished_people %>
							<dd><%= person_link_unchecked person %></dd>
						<% else %>
							<dd><%= person.full_name %></dd>
						<% end %>
					<% end %>
				</div>
			<% end %>
		</dl>
	</div>

	<div class="actions">
		<%= icon_button "Tabellenansicht", :grid_on, people_as_table_path %>
		<%= new_person_link %>
		<% if policy(@people).export? %>
			<%= download_json_button people_path(format: :json) %>
		<% end %>
		<%= sepa_export_button %>
	</div>
</article>