config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  get '/export', to: 'export#prepare'
  post '/export', to: 'export#export'
  get '/import', to: 'import#prepare'
  post '/import', to: 'import#import'
  get '/import_banking_statement', to: 'banking_statement_import#prepare'
  post '/import_banking_statement', to: 'banking_statement_import#import'
  get '/sepa_export', to: 'sepa_export#verify'
  post '/sepa_export', to: 'sepa_export#export'

  post '/admin/privileged_mode', to: 'admin#enable_privileged_mode'
  post '/admin/standard_mode', to: 'admin#disable_privileged_mode'

  get '/outstanding_payments', action: :show, controller: 'outstanding_payments'
  get '/finance_review', action: :show, controller: 'finance_review'

  resources :versions, only: %i[index show] do
    patch 'revert', to: 'versions#revert', on: :member
  end

  concern :versionable do
    resources :versions, only: %i[index show] do
      get 'diff', to: 'versions#diff'
      get 'diff/:after_id', to: 'versions#diff'
      patch 'revert', to: 'versions#revert'
    end
  end

  resources :password_resets # TODO: only

  get '/people_as_table', to: 'people#index_as_table'
  get '/events_as_table', to: 'events#index_as_table'

  root 'static#index'

  resources :people, concerns: :versionable do
    member do
      get 'addresses'
      get 'registrations'
      get 'privacy'
      get 'payments'
      get 'sepa_mandate'
      get 'groups'

      get 'edit_addresses'
      get 'edit_privacy'
      get 'edit_payments'
      get 'edit_sepa_mandate'
      delete 'delete_sepa_mandate', to: 'people#destroy_sepa_mandate'
      get 'edit_groups'

      get 'activate'
      post 'archive', to: 'people#archive'
    end
  end

  resources :registrations, concerns: :versionable do
    member do
      post 'self', to: 'registrations#create_self'
      get 'self', to: 'registrations#edit_self'
      put 'self', to: 'registrations#update_self'
      patch 'self', to: 'registrations#update_self'
      post 'pay_rest', to: 'registrations#pay_rest'
      get 'invitation', to: 'registrations#view_invitation', as: 'view_invitation'
    end
  end

  resources :events, concerns: :versionable do
    member do
      get 'registrations_as_table'
      get 'edit_own_registration'
      get 'edit_payments'
      get 'finances'
    end

    get 'register_other', to: 'registrations#select_person', as: 'select_person'
    post 'register_other', to: 'registrations#with_selected_person'
    get 'register_other/:person_id', to: 'registrations#new', as: 'register_person'
    post 'register_other/:person_id', to: 'registrations#create'
    get 'register_self', to: 'registrations#new_self'
    post 'register_self', to: 'registrations#create_self'
  end

  resources :generic_payments, concerns: :versionable
  resources :hostels, concerns: :versionable
  resources :groups, concerns: :versionable
  resources :mailinglists, concerns: :versionable

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_debug.erb
<details>
<summary>Debugmeldungen</summary>
<h3>Rechte</h3>
<b>Rails-Umgebung: <%= Rails.env %></b><br>
<% if logged_in? %>
<div class="debug" style="text-align: left">
<b>Status: </b>
<% unless current_user.nil? %>
<%= current_user.groups.where(event: nil).map{|g| g.title}.join(", ") %>
<% end %>
<dl>
<% if controller_name == 'people' %>
<dt>Person:</dt>
<dd><%= (policy(@person.nil? ? Person : @person).granted_list).to_s %></dd>
<dt>Person Attributes:</dt>
<dd><%= (policy(@person.nil? ? Person : @person).permitted_attributes).to_s %></dd>
<% end %>
<% if controller_name == 'events' %>
<dt>Event:</dt>
<dd><%= (policy(@event.nil? ? Event : @event).granted_list).to_s %></dd>
<dt>Event Attributes:</dt>
<dd><%= (policy(@event.nil? ? Event : @event).permitted_attributes).to_s %></dd>
<% end %>
<% if controller_name  == 'registrations' %>
<dt>Registration:</dt>
<dd><%= (policy(@registration.nil? ? Registration : @registration).granted_list).to_s %></dd>
<dt>Registration Attributes:</dt>
<dd><%= (policy(@registration.nil? ? Registration : @registration).permitted_attributes).to_s %></dd>
<% end %>
<% if controller_name == 'hostels' %>
<dt>Hostel:</dt>
<dd><%= (policy(@hostel.nil? ? Hostel : @hostel).granted_list).to_s %></dd>
<% end %>
<% if controller_name == 'groups' %>
<dt>Group:</dt>
<dd><%= (policy(@group.nil? ? Group : @group).granted_list).to_s %></dd>
<% end %>
<% if controller_name == 'mailinglists' %>
<dt>Mailinglist:</dt>
<dd><%= (policy(@mailinglist.nil? ? Mailinglist : @mailinglist).granted_list).to_s %></dd>
<% end %>
<dt>Version:</dt>
<dd><%= policy(PaperTrail::Version).granted_list.to_s %></dd>
<dt>Admin:</dt>
<dd><%= policy(:admin).granted_list.to_s %></dd>
</dl>
</div>
<% end %>
</details>

app/views/shared/_errors.erb
<% if object.errors.any? %>
<div class="error validation_error">
	<b><%= t('errors.template.header', :model => object.class.model_name.human, :count => object.errors.count) %></b><br>
	<%= t('errors.template.body') %>
	<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_menu_bar.erb
<header>
  <nav id="mainnav" class="horizontal">
    <%= link_to "Eigene Daten", person_path(current_user) %>
    <%= people_link %>
    <%= events_link %>
    <%= hostels_link %>
    <%= groups_link %>
    <%= mailinglists_link %>
    <%= versions_link %>
    <%= import_link %>
    <%= export_link %>
    <%= banking_statement_import_link %>
    <%= outstanding_payments_link %>
    <%= finance_review_link %>
    <%= generic_payments_link %>
    <%= privileged_mode_link %>
  </nav>
</header>

<nav class="breadcrumb">
  <ol>
    <% breadcrumb_trail.each do |crumb| %>
      <li>
        <%= link_to crumb.name,
        crumb.url,
        "aria-current":
          (
            if request.fullpath == crumb.url
              "page"
            else
              nil
            end
          ) %>
      </li>
    <% end %>
  </ol>
</nav>

<div class="mobilemenu">
  <%= icon_button "", :menu, "javascript:toggleHeader()" %>
</div>

<script>
function toggleHeader() {
	const menu = document.getElementsByTagName("header")[0];
	if(menu.style.visibility === "visible")
	{
		menu.style.visibility = "hidden";
		menu.style.opacity = "0%";
	}
	else
	{
		menu.style.visibility = "visible";
		menu.style.opacity = "95%";
	}
}
</script>